### PR TITLE
fix: Fix `PopoverArrow` placement on Safari

### LINKED ISSUE #1040: [V2] Popover arrow placement
[Popover](https://ariakit.org/examples/popover)

I noticed the arrow placement was off on iOS Safari. 

IMG_6263

I did some quick initial testing and it appears it isn't an issue on desktop chrome but it is an issue in desktop Safari. 
image

Doing some quick googling it looks like this is a known issue with Safari. https://stackoverflow.com/questions/48248512/svg-transform-rotate180-does-not-work-in-safari-11 and it looks like there might be an easy fix. I will try to dig in to this in the next day or two.

### PR DESCRIPTION
**Pull request by SCasarotto**
This PR closes #1040. 

The way to test:
- Boot in Safari, Chrome & Firefox 
- Open the Popover
- Reduce the height of the window to force the pop over to appear above the button

Screenshots of that testing:

Safari:
image
image

Chrome: 
image
image

Firefox:
image
image

### CODE REVIEW

File: packages/ariakit/src/popover/popover-arrow.tsx [hunk 1]
```diff
@@ -12,15 +12,16 @@ import { POPOVER_ARROW_PATH } from "./__popover-arrow-path";
...
 const rotateMap = {
-  top: "rotate(180 0 0)",
-  right: "rotate(-90 0 0)",
-  bottom: "rotate(0 0 0)",
-  left: "rotate(90 0 0)",
+  top: `rotate(180 ${halfDefaultSize} ${halfDefaultSize})`,
+  right: `rotate(-90 ${halfDefaultSize} ${halfDefaultSize})`,
+  bottom: `rotate(0 ${halfDefaultSize} ${halfDefaultSize})`,
+  left: `rotate(90 ${halfDefaultSize} ${halfDefaultSize})`,
 };
```
Comment (diegohaz) [inline packages/ariakit/src/popover/popover-arrow.tsx:23]: Thank you so much for researching and fixing this issue @SCasarotto! It works great.

I'm just trying to wrap my head around this `halfDefaultSize` logic. I can't see the difference between `rotate(180 15 15)` and `rotate(180)`. Could you add a comment explaining that?

I wonder if we could just do `rotate(180)`, `rotate(-90)` etc.

Comment (diegohaz) [reply packages/ariakit/src/popover/popover-arrow.tsx:23]: I see the difference now when the placement is `right` or `left`.

Comment (SCasarotto) [reply packages/ariakit/src/popover/popover-arrow.tsx:23]: When I try that on Chrome I see this:
image

Am I missing something?

Comment (SCasarotto) [reply packages/ariakit/src/popover/popover-arrow.tsx:23]: The halfDefaultSize moves the rotation origin to the center. If its not centered it rotates about its 0,0 point. 

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform#rotate

Comment (diegohaz) [reply packages/ariakit/src/popover/popover-arrow.tsx:23]: I see! That makes sense. That works even if we pass a different `size` prop to the `PopoverArrow` component, right?

Comment (diegohaz) [reply packages/ariakit/src/popover/popover-arrow.tsx:23]: > When I try that on Chrome I see this: image
> 
> Am I missing something?

You're right! I can see that as well.

**Review by diegohaz — APPROVED** [review]
Awesome! ❤️

**Comment by SCasarotto** [comment]
Oh shoot. @diegohaz I actually think your question was right. Looking at the code a bit more I would want to test something. I think the `viewBox`, the rotation center and the size might need to be related.

**Comment by SCasarotto** [comment]
I don't know this component that well yet to quickly test it. If I find something should I just open another PR?

**Comment by diegohaz** [comment]
Yep! I did some tests with the `size` prop and couldn't see any problem (but I may be doing something wrong). Feel free to open a follow-up PR if you find a better solution.

**Comment by SCasarotto** [comment]
Okay sounds good. 👍
