### PR TITLE
fix: Fix modal `Dialog` not opening when triggered by `MenuItem`

### LINKED ISSUE #1137: Dialog "setVisible" gets erroneously called with false when using a MenuItem to change the state
### Current behavior

Trying to open a controlled Dialog from a MenuItem (`onClick={() => setVisible(true)}`) fails when the Menu is `animated: true`.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/charming-payne-z4ej3y?file=/src/bug-demo.tsx
2. Open the Dialog with the button. It works.
3. Open the menu, and then click the "Open dialog" option. It doesn't work.

### Expected behavior

The Dialog opens correctly.

I have investigated a bit, and this is what I know:

- `setVisible` is being called with `false` after setting the state to true.
- I logged the times during render and when the method gets called and they were a few milliseconds apart, around 50-100ms. This is in coherent with the observed behavior that the Dialog is very briefly visible before hiding again, causing a quick flash.
- It only happens if the menu is configured as animated.
- It doesn't matter if the dialog is animated.

### Possible solutions

I'm not really sure.

### PR DESCRIPTION
**Pull request by DaniGuardiola**
Fixes #1137

### CODE REVIEW

**Comment by diegohaz** [comment]
Nice! Thanks, @DaniGuardiola!

Could you please push an empty commit just to trigger CodeSandbox again? I think it didn't use the repro on the issue because it was linked later (and I don't know how to rebuild it haha).

File: packages/ariakit/src/composite/composite-hover.ts [hunk 1]
```diff
@@ -71,6 +71,7 @@ export const useCompositeHover = createHook<CompositeHoverOptions>(
       // may lose some events if this component is unmounted, but others are
       // still mounted.
       addGlobalEventListener("mousemove", setMouseMoving, true);
+      addGlobalEventListener("mouseup", resetMouseMoving, true);
```
Comment (diegohaz) [inline packages/ariakit/src/composite/composite-hover.ts:76]: I'd add mousedown as well just in case `MenuItem` is triggering something on mouse down.
```suggestion
      // See https://github.com/ariakit/ariakit/issues/1137
      addGlobalEventListener("mousedown", resetMouseMoving, true);
      addGlobalEventListener("mouseup", resetMouseMoving, true);
```

**Comment by DaniGuardiola** [comment]
@diegohaz I committed your suggestion, so that should do the trick :)

File: packages/ariakit/src/composite/composite-hover.ts (hunk 1 above)
Comment (DaniGuardiola) [reply packages/ariakit/src/composite/composite-hover.ts:76]: Wait, I just realized this adds `mousedown` too. Does that even really matter though? My thinking was that `mouseup` would be enough

**Review by diegohaz — APPROVED** [review]
