### PR TITLE
fix(tscjs): fix typescript in cjs builds by using a separate type import

### LINKED ISSUE #2356: Can't find types with pnpm and moduleResolution=nodeNext
### Current behavior

I'm getting this error from `tsc`

```
src/quickstart/components/layout/Accordion/index.tsx:1:21 - error TS7016: Could not find a declaration file for module '@ariakit/react'. '/home/aron/src/ss/clients/tizra/evergreen/node_modules/.pnpm/@ariakit+react@0.1.6_react-dom@18.2.0_react@18.2.0/node_modules/@ariakit/react/cjs/index.cjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/ariakit__react` if it exists or add a new declaration (.d.ts) file containing `declare module '@ariakit/react';`

1 import * as AK from '@ariakit/react'
```

This was working for me with 2.0.0-next.43

### Steps to reproduce the bug

I couldn't repro this with codesandbox, maybe because it needs pnpm? Here's a minimal repo

https://github.com/agriffis/vite-ariakit-nodenext

```
git clone https://github.com/agriffis/vite-ariakit-nodenext
cd vite-ariakit-nodenext
pnpm i
pnpm tsc
```

### Expected behavior

tsc should be able to find the types

### Workaround

_No response_

### Possible solutions

_No response_

### PR DESCRIPTION
**Pull request by djMax**
Closes #2356

Taking this PR from another project as inspiration:
https://github.com/drwpow/openapi-typescript/pull/1360

This should fix ariakit-react typing in Typescript projects using NodeNext module/moduleresolution by explicitly pointing at a "cts" type definition file. It should not bother existing use cases but I left index.d.ts in the cjs module just in case.

### CODE REVIEW

File: scripts/build/utils.js [hunk 1]
```diff
@@ -38,12 +38,27 @@ export function getPackageJson(rootPath, prod = false) {
...
+        import: {
+          default: `./${join(esmDir, path)}.js`,
+          types: `./${join(cjsDir, path)}.d.ts`,
+        },
+        require: {
+          default: `./${join(cjsDir, path)}.cjs`,
+          types: `./${join(cjsDir, path)}.d.cts`,
+        },
+      };
+    }
```
Comment (diegohaz) [inline scripts/build/utils.js]: According to the [TypeScript documentation](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing), the `types` field should be listed first. However, the documentation also notes that it will search for a declaration file in the same location. So, I'm curious whether it's necessary to explicitly set it here.

Comment (djMax) [reply scripts/build/utils.js]: It is. But I could certainly flip the order. In terms of repro, should I do that just as a separate git repo or is there a more typical place to do that in ariakit? i.e. do we use stackblitz or some similar thing.

**Comment by djMax** [comment]
https://stackblitz-starters-j4p32y.stackblitz.io

**Comment by diegohaz** [comment]
> https://stackblitz-starters-j4p32y.stackblitz.io

Thanks! I couldn't access that page, but I could see the source code when I changed the URL to https://stackblitz.com/edit/stackblitz-starters-j4p32y.

Looks like there's no `"type": "module"` in the `package.json` file. What's the use case for using `"moduleResolution": "NodeNext"` in a CommonJS project?

File: scripts/build/utils.js (hunk 1 above)
Comment (diegohaz) [reply scripts/build/utils.js]: > It is.

Is it still necessary if you remove the `.d.ts` files from the folder, only leaving the `.d.cts` ones?

**Comment by djMax** [comment]
Because, like many people, we rely on things that cannot handle type: module just yet. ESM is a s**t show, we don't want ariakit being the thing forcing people to endure the pain (IMHO).

File: scripts/build/utils.js (hunk 1 above)
Comment (djMax) [reply scripts/build/utils.js]: If we only had the .d.cts, then we wouldn't be pointing to in properly in the global "types" key. All of this is premised on the idea that upstream users of ariakit should not be forced into type: module, as evidenced by the multiple build outputs and the multiple import paths. This PR just fixes that to include Typescript situations that do not rely on ESM.

**Comment by diegohaz** [comment]
I understand not every project can be ESM right now. And Ariakit doesn't force this option. My question was about using `"moduleResolution": "NodeNext"` rather than `"moduleResolution": "Node"` (where this problem doesn't exist) in a CommonJS project. Is there a use case for that?

**Comment by djMax** [comment]
The short answer is I'm not sure. The longer one is that I think all modern large projects seem to balance on the head of a pin with ESM: between Next.js, Typescript, Vitest, Jest, sindresorhus's refusal to do anything except ESM, webpack, Storybook, etc. So it is a supported setting (NodeNext for module/moduleResolution) and working for us everywhere, EXCEPT that for some reason Typescript gets confused about the exports if there is no separate type detail in the export key in package.json. I cannot begin to fathom all the intricacies of why or why our pin is not currently poking us in the eye.

**Comment by djMax** [comment]
https://www.totaltypescript.com/concepts/option-module-must-be-set-to-nodenext-when-option-moduleresolution-is-set-to-nodenext

**Review by diegohaz — APPROVED** [review]
I've updated the build script to copy all CJS declaration files to their corresponding `.d.cts` versions, so it also works with deep path imports. I tested locally with various combinations of `type`, `module`, and `moduleResolution` values, and everything appears to be functioning well.

**Comment by djMax** [comment]
Excellent, that is definitely better, so I appreciate it!
