### PR TITLE
fix: Fix Popover warning when placement is auto base

### LINKED ISSUE #1117: [v2] Tooltip throws a console.error when using auto placements
### Current behavior

When using `auto` placements the Tooltip throws a `console.error` with the following message:
```bash
Popper: "auto" placements require the "flip" modifier be present and enabled to work.
```

PS: Setting the `flip` property to either false or true doesn't change the outcome.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/focused-hypatia-ubj3dm?file=/src/index.js
2. See console logs

### Expected behavior

The app should not throw an error when using auto placements.

### Possible solutions

_No response_

### PR DESCRIPTION
**Pull request by georgekaran**
Closes #1117

### CODE REVIEW

File: packages/ariakit/src/popover/popover-state.ts [hunk 1]
```diff
@@ -140,7 +140,7 @@ export function usePopoverState({
           {
             // https://popper.js.org/docs/v2/modifiers/flip/
             name: "flip",
-            enabled: flip && dialog.mounted,
+            enabled: placement?.startsWith("auto") ?? (flip && dialog.mounted),
```
Comment (diegohaz) [inline packages/ariakit/src/popover/popover-state.ts:144]: Just for reference:
```suggestion
            // See https://github.com/ariakit/ariakit/issues/1117
            enabled: placement?.startsWith("auto") ?? (flip && dialog.mounted),
```

**Review by diegohaz — APPROVED** [review]
Thanks! 🚀
