### PR TITLE
Set data-focus-visible synchronously

### LINKED ISSUE #4083: Composite: `[data-focus-visible]` is applied with a noticeable delay
### Current behavior

Originally reported in https://github.com/WordPress/gutenberg/pull/64873 

In the PR linked above, we use the `data-active-item` to apply active (and hover) styles to a `Ariakit.Menu`, and the `data-focus-visible` to apply focus visible styles.

When using the keyboard to navigate the menu items, it can happen that the `data-active-item` styles are applied for a few frames before the `data-focus-visible` styles are (correctly) applied.

@diegohaz said:

> Yes, `data-focus-visible` is applied using `requestAnimationFrame`, but the delay is likely caused by React batching state updates rather than `rAF`. Could you please open an issue on https://github.com/ariakit/ariakit?

### Steps to reproduce the bug

- Open https://stackblitz.com/edit/cbdw6b?file=menu%2Fstyle.css,menu%2Findex.tsx&theme=dark
- Cycle through the active items using keyboard. Notive how, sometimes, the focused item flickers red before turning blue

### Expected behavior

The `data-focus-visible` attribute should be applied sooner, without delays. In the demo shared above, the item should not flicker red.

### Workaround

Using the native CSS `:focus-visible` selector in addition to `[data-focus-visible]` (as done in https://github.com/WordPress/gutenberg/pull/64873) — although this not ideal, as also explained in the [ariakit docs](https://ariakit.org/guide/styling#data-focus-visible)

Or https://github.com/ariakit/ariakit/issues/4083#issuecomment-2321244865

### Possible solutions

Maybe we should wrap the focus visible update in `flushSync` here:

https://github.com/ariakit/ariakit/blob/b2fdf603f8ee3506c022a8da155522b1a250b55f/packages/ariakit-react-core/src/focusable/focusable.tsx#L335

and here:

https://github.com/ariakit/ariakit/blob/b2fdf603f8ee3506c022a8da155522b1a250b55f/packages/ariakit-react-core/src/focusable/focusable.tsx#L350

See https://github.com/ariakit/ariakit/issues/4083#issuecomment-2321244865

### PR DESCRIPTION
**Pull request by diegohaz**
Closes #4083

This PR sets the `data-focus-visible` attribute without relying on React to update the `focusVisible` state internally. This ensures `data-focus-visible` and other attributes like `data-active-item` are updated simultaneously (visually).

I tried `ReactDOM.flushSync`, but aside from potentially hurting performance, there were a few React warnings about calling this in lifecycle methods. We could ignore these warnings, but setting the data attribute imperatively seems to be a safer option.

### CODE REVIEW

File: packages/ariakit-react-core/src/focusable/focusable.tsx [hunk 1]
```diff
@@ -343,6 +343,10 @@ export const useFocusable = createHook<TagName, FocusableOptions>(
       if (!hasFocus(element)) return;
       onFocusVisible?.(event);
       if (event.defaultPrevented) return;
+      // Make sure data-focus-visible is applied visually at the same time as
+      // other data attributes like data-active-item. See
+      // https://github.com/ariakit/ariakit/issues/4083
+      element.dataset.focusVisible = "true";
```
Comment (benrodrs) [inline packages/ariakit-react-core/src/focusable/focusable.tsx:349]: I assume React will retake control of this data attribute when `data-focus-visible` is set to `undefined`, thereby removing it from the DOM, right?

Comment (diegohaz) [reply packages/ariakit-react-core/src/focusable/focusable.tsx:349]: Yes, I've added an assertion to check that specifically:

https://github.com/ariakit/ariakit/blob/b4a440ed72dcaa811daa9067a29c58592996bc2f/examples/composite/test.ts#L74

But we already have other tests to ensure that. Just look for `not.toHaveAttribute("data-focus-visible")`.

**Review by benrodrs — APPROVED** [review]
